server:
  port: 8089

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/dreambungeo
    username: root
    password: coffee1592

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

